function [APARCLabels, APARCShortLabels] = freesurfer_statsurf_aparclabels(varargin)

% freesurfer_statsurf_aparclabels()
% 
% DESCRIPTION
%	Returns the long labels in order
%	If FreesurferSeedType = 'aparc' regions that have p < 0.05 will be
%	annotated automatically.nsclp_ctl

APARCLabels = {...
    'bankssts', ...
    'caudalanteriorcingulate', ...
    'caudalmiddlefrontal', ...
    'cuneus', ...
    'entorhinal', ...
    'fusiform', ...
    'inferiorparietal', ...
    'inferiortemporal', ...
    'isthmuscingulate', ...
    'lateraloccipital', ...
    'lateralorbitofrontal', ...
    'lingual', ...
    'medialorbitofrontal', ...
    'middletemporal', ...
    'parahippocampal', ...
    'paracentral', ...
    'parsopercularis', ...
    'parsorbitalis', ...
    'parstriangularis', ...
    'pericalcarine', ...
    'postcentral', ...
    'posteriorcingulate', ...
    'precentral', ...
    'precuneus', ...
    'rostralanteriorcingulate', ...
    'rostralmiddlefrontal', ...
    'superiorfrontal', ...
    'superiorparietal', ...
    'superiortemporal', ...
    'supramarginal', ...
    'frontalpole', ...
    'temporalpole', ...
    'transversetemporal', ...
    'insula'};

APARCShortLabels = {...
    'BSTS', ...
    'CAC', ...
    'CMF', ...
    'CUN', ...
    'ENT', ...
    'FUS', ...
    'INFP', ...
    'IT', ...
    'ISTC', ...
    'LOCC', ...
    'LORB', ...
    'LIN', ...
    'MORB', ...
    'MT', ...
    'PARH', ...
    'PARC', ...
    'POPE', ...
    'PORB', ...
    'PTRI', ...
    'PCAL', ...
    'PSTS', ...
    'PC', ...
    'PREC', ...
    'PCUN', ...
    'RAC', ...
    'RMF', ...
    'SF', ...
    'SP', ...
    'ST', ...
    'SMAR', ...
    'FP', ...
    'TP', ...
    'TT', ...
	'INS'};